### PR TITLE
🐛 Fix allEvents query input event type

### PR DESCRIPTION
**Pull request by XuTheBunny**
Screen Shot 2021-06-17 at 2 33 14 AM
Screen Shot 2021-06-17 at 2 33 26 AM

Error:
`Variable \"eventType\" of type \"String\" used in position expecting type \"EventEventType\".`

Fixed by:
In `allEvents` query input change `$eventType: String` to `$eventType: EventEventType`

### CODE REVIEW

**Comment by dankolbman** [comment]
Was this a regression that got introduced maybe with the version upgrades or was it there already?

**Review by znatty22 — COMMENTED** [review]
Just wondering when did this bug get introduced/how was stuff working before

**Comment by dankolbman** [comment]
Looks like this change was introduced with an upgrade to the latest graphene: https://github.com/kids-first/kf-api-study-creator/commit/bf500248a313643d48cdabee2b82285375677ef9

**Review by dankolbman — APPROVED** [review]
👍

**Pull request merged**
