### PR TITLE
✨ Add template admin view with create/edit/delete template function

### LINKED ISSUE #1067: Manage Data Templates View
## Feature Justification

In order to support the upcoming data templates features detailed in https://github.com/kids-first/kf-api-study-creator/pull/647, we will need to give users a way to browse all existing templates.

## Proposed Change or Addition

- [x] Add a new menu item `Data Templates` to the Admin menu. Clicking it should take the user to the Manage Data Templates View
- [x] Implement a view to list and browse for data templates. The design should roughly follow the wireframes here:

https://docs.google.com/presentation/d/101n1uKvORAuXjCG8BiBYDFgfwkvpW5NqXqsXdn4s6xY/edit?usp=sharing

### LINKED ISSUE #1069: Create New Data Template flow
## Feature Justification

In order to support the upcoming data templates features detailed in https://github.com/kids-first/kf-api-study-creator/pull/647, we will need to give users a way create new templates.

## Proposed Change or Addition

Implement the Create New Data Template flow in:

https://docs.google.com/presentation/d/101n1uKvORAuXjCG8BiBYDFgfwkvpW5NqXqsXdn4s6xY/edit?usp=sharing

This issue should focus on getting the 3-step layout and template basic info form implemented. There will be other issues to implement other pieces of this flow (Template Field List, Add Field Form, etc)

### LINKED ISSUE #1070: Add/remove/edit template field UI
## Feature Justification

In order to support the upcoming data templates features detailed in https://github.com/kids-first/kf-api-study-creator/pull/647, we will need to give users a way add/remove/edit fields in their templates.

## Proposed Change or Addition

Implement the functionality (except for the Import Fields feature) in the Add Fields view in:

https://docs.google.com/presentation/d/101n1uKvORAuXjCG8BiBYDFgfwkvpW5NqXqsXdn4s6xY/edit?usp=sharing

- [x] Add Field button
- [x] Add Field form
- [x] Edit Field button
- [x] Edit Field form (should be same as Add Field Form with minor differences)
- [x] Delete template button

### LINKED ISSUE #1071: Import Fields
## Feature Justification

In order to support the upcoming data templates features detailed in https://github.com/kids-first/kf-api-study-creator/pull/647, we will need to give users a way upload the field definitions for their template.

## Proposed Change or Addition

Implement the import fields functionality in:

https://docs.google.com/presentation/d/101n1uKvORAuXjCG8BiBYDFgfwkvpW5NqXqsXdn4s6xY/edit?usp=sharing

- [x] Fields List View (no need to implement edit/delete buttons until later)
- [x] Import Fields button
- [x] Import Fields modal

### LINKED ISSUE #1072: Add/remove templates to/from studies
## Feature Justification

In order to support the upcoming data templates features detailed in https://github.com/kids-first/kf-api-study-creator/pull/647, we will need to give users a way add/remove templates to/from their studies.

## Proposed Change or Addition

Implement the add/remove templates view in:

https://docs.google.com/presentation/d/101n1uKvORAuXjCG8BiBYDFgfwkvpW5NqXqsXdn4s6xY/edit?usp=sharing

- [x] Manage Study Templates button on Manage Data Templates View
- [x] View for add/remove templates to/from studies

### LINKED ISSUE #1074: Update Template Flow
## Feature Justification

In order to support the upcoming data templates features detailed in https://github.com/kids-first/kf-api-study-creator/pull/647, we will need to give users a way update existing templates.

## Proposed Change or Addition

Implement the Update template flow in:

https://docs.google.com/presentation/d/101n1uKvORAuXjCG8BiBYDFgfwkvpW5NqXqsXdn4s6xY/edit?usp=sharing

This should try to reuse a lot of the components in the Create New Data Template workflow.

### PR DESCRIPTION
**Pull request by XuTheBunny**
List out all templates:
Screen Shot 2021-08-06 at 8 56 55 PM

Create template basic info:
Screen Shot 2021-08-06 at 7 58 00 PM

Create template select icon:
Screen Shot 2021-08-06 at 7 58 40 PM

Create template no fields added:
Screen Shot 2021-08-06 at 7 58 08 PM

Create template add field:
Screen Shot 2021-08-06 at 7 58 50 PM

Create template import fields:
Screen Shot 2021-08-06 at 7 59 05 PM

Create template select studies:
Screen Shot 2021-08-06 at 7 58 18 PM

Edit existing template:
Screen Shot 2021-08-06 at 8 01 35 PM

Edit template confirm modal:
Screen Shot 2021-08-06 at 8 05 21 PM

Close #1074
Close #1072
Close #1071
Close #1070
Close #1069
Close #1067

### CODE REVIEW

**Review by znatty22 — COMMENTED** [review]
Few requests, I'll just leave them here: 

- [x] 1. Can we position the create button on top of and to the right of the templates list segment when there are no templates in the admin view? To keep it consistent with the look when the list is populated

image

- [x] 2. Create/Edit Template: icon selection- it seems like a lot of semantic icons are missing from the menu? I wanted to select one of the health icons but i don't see any in the menu

- [ ] 3. Create/Edit Template Form: add row
    - The `Label` input is showing my password manager icon, is it a password input type?
    - Can you disable Accepted Values unless the Data Type is enum?
    - There is a missing column (sorry I made this change later). See https://github.com/kids-first/kf-api-study-creator/blob/881096ea955b521d0527c966baa07d852157542a/creator/data_templates/field_definitions_schema.py#L122

- [ ] 4. The font sizes look a little funny to me in this view - it'll be easier to chat about this one
image

- [ ] 5. Delete template - The delete template button doesn't work yet - is this intended to be implemented in another PR?

- [x] 6. Download template - since this functionality isn't available from admin view yet, could we change the message in the info bubble on hover to say something like: `Feature not available yet. Download templates from Study view` or maybe just hide the button for now? idk what's better

- [ ] 7. Templates from another org don't seem to render correctly in the list

image

- [ ] 8. The user should be able to view any template (regardless of organization) however, they may only edit or delete templates from organization(s) they are a member of

- [ ] 9. This template is owned by `Default Organization` however, the edit form is populating the organization input with `Magical Memes` (logged in user's org)
image

 
- [ ] 10. Not sure if I am doing something wrong but after I create a template and assign it to a study, I'm not seeing my template show up in the study data templates tab

**Comment by znatty22** [comment]
12. The `Key` column does not get imported when importing fields from file. The column also doesn't appear in the Fields list

**Comment by dankolbman** [comment]
screenshot




<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Firefox 90.0 on Mac OS 10.15
Viewport:  1440 x 815 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=90.0&resolution=1440x815&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=610ab48c56224d00089fe911&commentID=610adad423b64708ccd88c67&resolution=resolved)

**Comment by dankolbman** [comment]
screenshot

If it's not too difficult, it would be nice to be able to have this be more like an autocomplete drop down. Sort of like [this](https://react.semantic-ui.com/modules/dropdown/#types-search-dropdown) but with the icon and name inline. That way I could search 'pic' and have it narrow down to the 'picture' icon.
<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Firefox 90.0 on Mac OS 10.15
Viewport:  1440 x 815 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=90.0&resolution=1440x815&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=610ab48c56224d00089fe911&commentID=610adc2193ac880915ea3056&resolution=resolved)

**Comment by dankolbman** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Firefox 90.0 on Mac OS 10.15
Viewport:  1440 x 815 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=90.0&resolution=1440x815&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=610ab48c56224d00089fe911&commentID=610adc9834e177098cc68a7b&resolution=resolved)

**Comment by dankolbman** [comment]
screenshot

Minor gripe, but clicking on the overly closes the modal. This isn't usually a big deal, but adding each field manually can be a lot of work and can easily be lost if the user clicks in the wrong spot accidentally.
<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Firefox 90.0 on Mac OS 10.15
Viewport:  1440 x 815 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=90.0&resolution=1440x815&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=610ab48c56224d00089fe911&commentID=610addddd0e9140813a971bd&resolution=resolved)

**Comment by dankolbman** [comment]
screenshot

Would it make more sense to put the label first here?


<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Firefox 90.0 on Mac OS 10.15
Viewport:  1440 x 815 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=90.0&resolution=1440x815&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=610ab48c56224d00089fe911&commentID=610ade20cab3c908a4a62277&resolution=resolved)

**Comment by dankolbman** [comment]
screenshot

Clicking the save button here takes me to a confirmation screen which:
1) Is not clear that it is a confirmation, the designs are almost identical and my attention is not drawn tho the 'confirm' part
2) Not clear that I would be asked to confirm
3) I'm not really sure why I need to confirm this action, especially when I don't need to for other actions
4) Confirming on the next screen doesn't do anything (Maybe just an issue with the api, but still no error message is displayed)

<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Firefox 90.0 on Mac OS 10.15
Viewport:  1440 x 815 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=90.0&resolution=1440x815&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=610ab48c56224d00089fe911&commentID=610adf783cce5307cd09bd90&resolution=resolved)

**Comment by dankolbman** [comment]
screenshot

Seeing as we may want to have 'Admins' for each org, but not allow each admin to see _everything_, only their org, perhaps we should limit this view to only the active organization's templates.
<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Firefox 90.0 on Mac OS 10.15
Viewport:  1440 x 815 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=90.0&resolution=1440x815&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=610ab48c56224d00089fe911&commentID=610ae01f23b64709afd88f0c&resolution=resolved)

**Comment by znatty22** [comment]
> Seeing as we may want to have 'Admins' for each org, but not allow each admin to see everything, only their org, perhaps we should limit this view to only the active organization's templates.

I reeeally think an admin should always be able to view and download any template regardless of the organization that owns it. This will allow other template authors to build off of existing templates if they don't want to start from scratch.

**Comment by znatty22** [comment]
@dankolbman 

> 3. I'm not really sure why I need to confirm this action, especially when I don't need to for other actions

Yea this might be a little confusing. What's really happening is two mutations are going out: `UpdateDataTemplate` and `UpdateTemplateVersion`. For the `UpdateTemplateVersion` one you have to provide the required `description` field so this confirmation is sort of a way to prompt the user to describe the changes they made. I also saw that Xu added a feature that shows you a "diff" (added/removed fields) between the fields that were there and the ones you're submitting. That's kinda neat. 

However, if we really don't like this confirmation then we could do either of the following: 1) Make the `TemplateVersion.description` field optional or always populate it with some default message since I _believe_ in this MVP we are always mutating the first and only `TemplateVersion`

> 4. Confirming on the next screen doesn't do anything (Maybe just an issue with the api, but still no error message is displayed)

I've experienced the same thing

**Comment by znatty22** [comment]
> IMO, it should be 'Add Field' to stay consistent with the 'Import Fields' 

Initially I liked the `Add Row` label bc I thought it's immediately clear as to what that will do, but I'm thinking about it again. Let's go with `Add Field` to stay consistent with `Import Fields`

**Comment by znatty22** [comment]
> Its a little confusing what these arrows do

I was feeling the same way. I think in other walkthrough views those buttons are `Next` and `Back` with the appropriate arrow icons. Maybe that would be more clear?

**Comment by znatty22** [comment]
screenshot

Can this default to the organization that the logged in user has switched to?


<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Chrome 92.0.4515.107 on Mac OS 10.15.7
Viewport:  1440 x 798 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1440x798&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=610e00323cbf70000775e7e0&commentID=611146e2d04c4900bc8f68ef&resolution=resolved)

**Comment by znatty22** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Chrome 92.0.4515.107 on Mac OS 10.15.7
Viewport:  1440 x 798 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1440x798&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=610e00323cbf70000775e7e0&commentID=611147c4b9f79600b5b86692&resolution=resolved)

**Comment by znatty22** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Chrome 92.0.4515.107 on Mac OS 10.15.7
Viewport:  2023 x 1361 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=2023x1361&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6111f88345877a00087605f5&commentID=6112c086b575145f2845709e&resolution=resolved)

**Comment by znatty22** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Chrome 92.0.4515.107 on Mac OS 10.15.7
Viewport:  2023 x 1361 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=2023x1361&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6111f88345877a00087605f5&commentID=6112c0ef1bf48672cbe6de58&resolution=resolved)

**Comment by znatty22** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /study/SD_ME0WME0W/templates
Browser:   Chrome 92.0.4515.107 on Mac OS 10.15.7
Viewport:  2023 x 1361 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Fstudy%2FSD_ME0WME0W%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=2023x1361&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/study/SD_ME0WME0W/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6111f88345877a00087605f5&commentID=6112c24e148ef57824419404&resolution=resolved)

**Comment by znatty22** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Chrome 92.0.4515.107 on Mac OS 10.15.7
Viewport:  2560 x 1338 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=2560x1338&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6112e5c9798d25000792aef5&commentID=6113080fc0b3a50cf99f3dc3&resolution=resolved)

**Comment by znatty22** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /templates
Browser:   Chrome 92.0.4515.107 on Mac OS 10.15.7
Viewport:  2560 x 1338 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1085--kf-ui-data-tracker.netlify.app%2Ftemplates&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=2560x1338&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1085--kf-ui-data-tracker.netlify.app/templates) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6112e5c9798d25000792aef5&commentID=611308f69ac96b11dfa35523&resolution=resolved)

**Review by znatty22 — APPROVED** [review]
Looks good to me, great work @XuTheBunny! I would suggest updating the PR title to include create, edit, delete template functions

**Review by dankolbman — APPROVED** [review]
# 🛶

**Pull request merged**
