### PR TITLE
✨ Add investigator to study

### LINKED ISSUE #889: Investigator/Contacts
**Sender**: heathap@email.chop.edu
**Comment**: Was expecting being able to see the investigators(s) for the study on this page? Also wondering if we need three tabs or easier to see all of the details on one page?
[Open #62 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/62)

<a href='https://usersnappublic.s3.amazonaws.com/2020-09-18/18-20/dcf9519d-6bf6-4d37-b954-f9fe68994fe6.png'>⚠️ - Investigator/Contacts</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-09-18/18-20/dcf9519d-6bf6-4d37-b954-f9fe68994fe6.png'>Download original image</a>

**Browser**: Firefox 80 (macOS Mojave)
**Referer**: [https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_Q2F7XA29/basic-info/info](https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_Q2F7XA29/basic-info/info)
**Screen size**: 2560 x 1440 **Browser size**: 1765 x 1097

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

### PR DESCRIPTION
**Pull request by dankolbman**
Adds an investigator name to studies to aid in organizing and finding studies.

Visible and modifyable in new study form and study info form.
Available as a column in the study table.
Searchable from the study table.

## Visual Changes
Screen Shot 2021-02-23 at 11 46 20 AM

Screen Shot 2021-02-23 at 12 31 46 PM

Screen Shot 2021-02-23 at 1 13 09 PM

Closes #889

### CODE REVIEW

**Review by znatty22 — CHANGES_REQUESTED** [review]

**Review by znatty22 — CHANGES_REQUESTED** [review]
image

**Review by XuTheBunny — APPROVED** [review]
🥐

**Review by znatty22 — CHANGES_REQUESTED** [review]
Looks like the error isn't cleared after you close and reopen the edit modal for the investigator that had an error before

**Review by znatty22 — APPROVED** [review]
⚗️

**Pull request merged**
